server:
  port: 7979

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true 

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    auth-route:
      path: /auth/**
      sensitiveHeaders:
      service-id: cloud-mall-provider-sso
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    order-route:
      path: /order/**
      sensitiveHeaders:
      service-id: cloud-mall-provider-order
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    user-route:
      path: /user/**
      sensitiveHeaders:
      service-id: cloud-mall-provider-user
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000 

#如果Zuul使用服务发现，则需要使用
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#熔断机制超时
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
